name: CI

on: [push]

jobs:
  Sast_scan:
    name: Run Bandit Scan
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: set up Python
      uses: actions/setup-python@v6.2.0
      with:
        python-veersion: 3.8

        -name: install Bandit
        run: pip install bandit

        name: Run Bandit Scan
